/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 18 06:27:23 GMT 2017
 */

package edu.osu.cs362;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import edu.osu.cs362.Mergesort;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Mergesort_ESTest extends Mergesort_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Mergesort mergesort0 = null;
      try {
        mergesort0 = new Mergesort((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("edu.osu.cs362.Mergesort", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int[] intArray0 = new int[5];
      intArray0[0] = (-1043);
      intArray0[1] = (-2960);
      intArray0[2] = 0;
      intArray0[3] = 0;
      intArray0[4] = 0;
      Mergesort mergesort0 = new Mergesort(intArray0);
      mergesort0.getAt(0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int[] intArray0 = new int[9];
      intArray0[0] = 1114;
      intArray0[1] = 0;
      intArray0[2] = 0;
      intArray0[3] = 0;
      intArray0[4] = (-1);
      intArray0[5] = 0;
      intArray0[6] = 1;
      intArray0[7] = (-1695);
      intArray0[8] = 863;
      Mergesort mergesort0 = new Mergesort(intArray0);
      mergesort0.mergesort(1927, 5271);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      int[] intArray0 = new int[9];
      intArray0[0] = (-3007);
      intArray0[1] = 0;
      intArray0[2] = 2539;
      intArray0[3] = 1;
      intArray0[4] = 562;
      intArray0[5] = (-1675);
      intArray0[6] = 0;
      intArray0[7] = (-1);
      intArray0[8] = (-2803);
      Mergesort mergesort0 = new Mergesort(intArray0);
      // Undeclared exception!
      try { 
        mergesort0.getAt(562);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 562
         //
         assertThrownBy("edu.osu.cs362.Mergesort", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Mergesort mergesort0 = new Mergesort();
      Mergesort mergesort1 = new Mergesort();
      int[] intArray0 = new int[7];
      intArray0[0] = 367;
      intArray0[1] = (-969);
      intArray0[2] = 0;
      intArray0[3] = 0;
      intArray0[4] = 20;
      intArray0[5] = 0;
      intArray0[6] = 1;
      Mergesort mergesort2 = new Mergesort(intArray0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      int[] intArray0 = new int[6];
      intArray0[0] = 2;
      intArray0[1] = 2;
      intArray0[2] = (-1);
      intArray0[3] = (-2621);
      intArray0[4] = 0;
      intArray0[5] = 0;
      Mergesort mergesort0 = new Mergesort(intArray0);
      mergesort0.mergesort((-4239), 0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Mergesort mergesort0 = new Mergesort();
      int int0 = 0;
      // Undeclared exception!
      try { 
        mergesort0.getAt(0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("edu.osu.cs362.Mergesort", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      int[] intArray0 = new int[4];
      intArray0[0] = 0;
      intArray0[1] = (-4330);
      intArray0[2] = 1;
      intArray0[3] = 0;
      Mergesort mergesort0 = new Mergesort(intArray0);
      mergesort0.sort(intArray0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Mergesort mergesort0 = new Mergesort();
      int int0 = 2;
      // Undeclared exception!
      try { 
        mergesort0.getAt(2);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("edu.osu.cs362.Mergesort", e);
      }
  }
}
